# Abstract

Bullying in online games is a serious problem and online chess is no exception. The purpose of trash talking is to try to decrease opponent performance by distracting opponents into heightened emotions and less logical decision making.  However, these tactics may actually  backfire. In our study, opponents were randomly selected by the lichess.org matching algorithm and we randomly assigned these opponents to a control, placebo, or treatment group at time of matching. For those in the treatment group, they received non-harassing standardized comments about the inaccuracies in their play. In our follow-up experiment, we implemented the OpenAI API so that we could use ChatGPT 4.0 to engage with players more dynamically to more directly measure any effects of a conversation. Similar to our first experiment, we randomly assigned opponents into control and ChatGPT. Our analysis for both experiments did not produce any significant effects across multiple outcomes. Since chatting with an opponent in online gaming, particularly in chess, has mixed reviews from players, this lack of effect may be useful information to players who are opposed to chatting, knowing that it was not found to have any adverse effects on opponents.
